module.exports = {
  kospi: require('./kospi.js'),
  kosdaq: require('./kosdaq.js'),
  foreignKospi : require('./foreignKospi'),
  foreignKosdaq : require('./foreignKosdaq'),
  dow : require('./dow'),
  nasdaq : require('./nasdaq'),
  tenminustwo : require('./tenminustwo'),
  bdi: require('./bdi.js'),
  // bondinterest: require('./bondinterest.js'),
  // consumersales: require('./consumersales.js'),
  creditbalance: require('./creditbalance.js'),
  // employmentrate: require('./employmentrate.js'),
  exchangerate: require('./exchangerate.js'),
  // futuresoptiontrend: require('./futuresoptiontrend.js'),
  koreanexport: require('./koreanexport.js'),
  oilprice: require('./oilprice.js'),
  hotrolled: require('./hotrolled.js'),
  pmi: require('./pmi.js'),
  vix: require('./vix.js'),
};